#!/data/data/com.termux/files/usr/bin/sh

# Termux Plugin Installation Script - Phase 2
# Installs required Termux plugins

echo "=========================================="
echo "  Termux Plugin Installation Guide"
echo "=========================================="
echo ""
echo "Install these plugins from F-Droid or GitHub:"
echo ""
echo "1. Termux:API"
echo "   Package: com.termux.api"
echo "   Purpose: Access Android APIs from command line"
echo "   Install: https://f-droid.org/packages/com.termux.api/"
echo ""
echo "2. Termux:Boot"
echo "   Package: com.termux.boot"
echo "   Purpose: Run scripts at device boot"
echo "   Install: https://f-droid.org/packages/com.termux.boot/"
echo ""
echo "3. Termux:Tasker"
echo "   Package: com.termux.tasker"
echo "   Purpose: Integrate with Tasker automation"
echo "   Install: https://f-droid.org/packages/com.termux.tasker/"
echo ""
echo "4. Termux:Widget"
echo "   Package: com.termux.widget"
echo "   Purpose: Home screen shortcuts"
echo "   Install: https://f-droid.org/packages/com.termux.widget/"
echo ""
echo "5. Termux:Float (optional)"
echo "   Package: com.termux.float"
echo "   Purpose: Floating terminal window"
echo "   Install: https://f-droid.org/packages/com.termux.float/"
echo ""
echo "6. Termux:Styling (optional)"
echo "   Package: com.termux.styling"
echo "   Purpose: Custom terminal themes"
echo "   Install: https://f-droid.org/packages/com.termux.styling/"
echo ""
echo "IMPORTANT: All plugins must be from the same source"
echo "(all F-Droid or all GitHub) to work together!"
echo ""
echo "After installing, run: termux-setup-storage"
echo "to grant storage permissions if needed."
echo ""
echo "Phase 2 complete!"
